dist: trusty
language: python
addons:
  apt:
    update: true
python:
  - "3.6"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
# command to run tests
script:
  - python test_script.py
